{% set name = "lpdr" %}
{% set version = "0.2a20201028" %}
{% set git_tag = "ef43c83b07c17c2e2c4dfb2c58f44abe688e424b" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/szachovy/lpdr/archive/{{ git_tag }}.tar.gz
  sha256: a49ec0134f8ef832cd67e75082f2214f656f571a2916f7692e7333528a5b137c

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - keras >=2.3.1
    - numpy >=1.17.4
    - opencv
    - pytesseract >=0.3.4
    - python >=3.7
    - tensorflow

test:
  imports:
    - lpdr

about:
  home: https://pypi.org/project/lpdr/
  summary: License Plate Detector and Recognizer
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mxr-conda
    - oblute
    - JennaLipscomb
